name       : python-hatch-fancy-pypi-readme
version    : 22.8.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/h/hatch_fancy_pypi_readme/hatch_fancy_pypi_readme-22.8.0.tar.gz : da91282ca09601c18aded8e378daf8b578c70214866f0971156ee9bb9ce6c26a
homepage   : https://github.com/hynek/hatch-fancy-pypi-readme
license    : MIT
component  : programming.python
summary    : Fancy PyPI READMEs with Hatch 
description: |
    hatch-fancy-pypi-readme is a Hatch metadata plugin for everyone who cares about the first impression of their project’s PyPI landing page. It allows you to define your PyPI project description in terms of concatenated fragments that are based on static strings, files, and most importantly: parts of files defined using cut-off points or regular expressions.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-hatchling
build      : |
    %python3_setup
install    : |
    %python3_install
